# Generated by Django 5.2.8 on 2025-11-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cuenta', models.CharField(max_length=20, unique=True)),
                ('nombre_cuenta', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], max_length=10)),
                ('empleados', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprovacion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_creadas', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('subempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.subempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_debito', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monto_credito', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cuenta')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.subempresa')),
            ],
        ),
    ]
