# Generated by Django 5.2.5 on 2025-11-27 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria del grupo de sub-empresas.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Subempresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subempresas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sub-empresa',
                'verbose_name_plural': 'Sub-empresas',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='subempresa',
            field=models.ForeignKey(blank=True, help_text='Sub-empresa sobre la que se registra el movimiento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.subempresa'),
        ),
        migrations.CreateModel(
            name='EmpresaSubempresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, help_text='Participación de la empresa en la sub-empresa (opcional).', max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_subempresas', to='core.empresa')),
                ('subempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_empresa', to='core.subempresa')),
            ],
            options={
                'verbose_name': 'Relación empresa-subempresa',
                'verbose_name_plural': 'Relaciones empresa-subempresa',
                'unique_together': {('empresa', 'subempresa')},
            },
        ),
    ]
