# Generated by Django 5.2.8 on 2025-11-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movimiento_empresa_subempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='subempresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='core.subempresa'),
        ),
    ]
