# Generated by Django 5.2.5 on 2025-12-01 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuarioempresa_subempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción corta que aparecerá en los reportes detallados.', max_length=255),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', help_text='Estado del movimiento para flujos de aprobación.', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='folio',
            field=models.CharField(blank=True, db_index=True, help_text='Folio o referencia externa opcional, útil para búsquedas y reportes.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='esta_pagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_pago',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'subempresa', 'fecha_registro'], name='mov_emp_sub_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'tipo'], name='mov_emp_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'concepto'], name='mov_emp_concepto_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['movimiento', 'fecha_vencimiento'], name='pago_mov_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_vencimiento', 'esta_pagado'], name='pago_fecha_pagado_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuarioempresa',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa', 'subempresa'), name='unique_usuario_empresa_subempresa'),
        ),
    ]
