# Generated by Django 5.2.5 on 2025-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuarioempresa_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='frecuencia_pago',
            field=models.CharField(choices=[('UNICO', 'Único'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='UNICO', max_length=10),
        ),
    ]
